import Head from "next/head";

import {Roboto } from "next/font/google";
import "./globals.css";

import Header from "#/shared/ui/Header/Header";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Movies App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}
      >
        <Head>
          <meta name="robots" content="noindex" key="robots" />
          <link rel="icon" href={`./next.svg`} />
          <title>{metadata.title}</title>
          <meta property="og:title" content={metadata.title} key="title" />
        </Head>

        <Header goBackButton />
        {children}
      </body>
    </html>
  );
}
